### ISSUE TITLE
BUG PGD_safe_screening solver install is failing

### ISSUE THREAD

**Issue by jolars** [benchopt/benchmark_slope#14]
I am getting the following error when trying to install the PGD_safe_screening solver:

```shell
- PGD_safe_screening
...Collecting git+https://gitlab-research.centralesupelec.fr/2020elvirac/slope-screening@master
  Cloning https://gitlab-research.centralesupelec.fr/2020elvirac/slope-screening (to revision master) to /tmp/pip-req-build-aknkn2gh
  Running command git clone --filter=blob:none --quiet https://gitlab-research.centralesupelec.fr/2020elvirac/slope-screening /tmp/pip-req-build-aknkn2gh
  warning: redirecting to https://gitlab-research.centralesupelec.fr/2020elvirac/slope-screening.git/
  Resolved https://gitlab-research.centralesupelec.fr/2020elvirac/slope-screening to commit fe3db9799b6355fef23c02903b9187606e739136
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-aknkn2gh/setup.py", line 3, in <module>
          from Cython.Build import cythonize
      ModuleNotFoundError: No module named 'Cython'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
```

It seems like there is no `install_requires` in the setup.py file for the repository, and I cannot get the installer to accept requirements.txt file that is in the repo from the interface. Adding the requirements manually in `requirements` for the sovler does not help either.

**Comment by jolars** [comment]
This was fixed in [64b977b](https://github.com/benchopt/benchmark_slope/pull/23/commits/64b977b843b92f01fbc046397e3f896891fd4ed3)
