### ISSUE TITLE
BUG ModuleNotFound error for rSLOPE (rpy2)

### ISSUE THREAD

**Issue by jolars** [benchopt/benchmark_slope#15]
When I am trying to install the rSLOPE solver, I run into this issue:

```shell
Traceback (most recent call last):
  File "/home/gerd-jln/projects/benchmark_slope/solvers/rslope.py", line 6, in <module>
    from benchopt.helpers.r_lang import import_rpackages
  File "/home/gerd-jln/.conda/envs/benchopt/lib/python3.10/site-packages/benchopt/helpers/r_lang.py", line 9, in <module>
    import rpy2  # noqa: E402
ModuleNotFoundError: No module named 'rpy2'
```

I think the code in https://github.com/benchopt/benchmark_slope/blob/main/solvers/rslope.py seems to correspond to the instructions here: https://benchopt.github.io/benchmark_workflow/write_benchmark.html

It still tries to install the requirements for the rSLOPE package, however, and then fails for some dependency issue, which I think is unrelated. 

I am not sure if this is related to https://github.com/benchopt/benchopt/issues/597?

**Comment by jolars** [comment]
I cannot reproduce this anymore, so I am closing now. Reopen if it's still an issue.
